version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      - "TZ=Japan"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./volumes:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
